apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  role: "arn:aws:iam::651706780852:role/KarpenterNodeRole-adritest"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: adritest
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: adritest
  tags:
    app.kubernetes.io/created-by: eks-workshop
